<?php
$tours = [
    [
        'name' => 'Sunny Beach',
        'country' => "US",
        'stars' => "4",
        'price' => "750",
        'transport' => "airplane",
    ],
    [
        'name' => 'Dark Woods',
        'country' => "France",
        'stars' => "5",
        'price' => "850",
        'transport' => "train",
    ],
    [
        'name' => 'Foggy Forest',
        'country' => "UK",
        'stars' => "3",
        'price' => "500",
        'transport' => "bus",
    ],
    [
        'name' => 'Hot Sea',
        'country' => "Mexico",
        'stars' => "2",
        'price' => "200",
        'transport' => "airplane",
    ],
    [
        'name' => 'Stanning Mountains',
        'country' => "Japan",
        'stars' => "4",
        'price' => "750",
        'transport' => "airplane",
    ],
    [
        'name' => 'Beautiful Walley',
        'country' => "US",
        'stars' => "1",
        'price' => "100",
        'transport' => "bus",
    ],
    [
        'name' => 'Yellow Desert',
        'country' => "Mexico",
        'stars' => "1",
        'price' => "100",
        'transport' => "bus",
    ],
    [
        'name' => 'Cozy Bay',
        'country' => "Japan",
        'stars' => "3",
        'price' => "550",
        'transport' => "train",
    ],
    [
        'name' => 'Huge Forest',
        'country' => "UK",
        'stars' => "3",
        'price' => "600",
        'transport' => "bus",
    ],
];